import Head from "next/head";
import { AboutUs, ClassLists, Footer, Header } from "@/components/layoutHome";
import { Container } from "react-bootstrap";
import { GetServerSideProps } from "next";
import Loader from "@/components/loader";

interface Props {
  courses: [{ [key: string]: string | number }];
}

export default function Home({ courses }: Props) {
  return (
    <>
      <Head>
        <title>KafeKoding | IT Community</title>
        <meta name="description" content="Generated by Kafekoding Community" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Loader />

      <Header />

      <Container>
        <ClassLists courses={courses} />
        <AboutUs />
      </Container>

      <Footer />
    </>
  );
}

async function getCourses() {
  const response = await fetch(`${process.env.API_LOCAL_SERVER}/api/courses`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
    cache: "no-store",
    next: { revalidate: 10 },
  });

  if (!response.ok) {
    console.log("error fetch data courses");
    return [];
  } else {
    return await response.json();
  }
}

export const getServerSideProps: GetServerSideProps = async () => {
  // if (typeof context.req.headers.authorization === "undefined") {
  //   return {
  //     redirect: {
  //       destination: "/login",
  //       permanent: false,
  //     },
  //   };
  // }
  const courses = await getCourses();
  return {
    props: {
      courses: courses,
    },
  };
};
